import { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PublicSharedSession } from "@mila/shared";
import { BrandLogo } from "@/components/brand-logo";
import { apiFetch } from "@/lib/api-server";

interface SharePageProps {
  params: Promise<{ token: string }>;
}

export const dynamic = "force-dynamic";

async function loadShared(token: string): Promise<PublicSharedSession | null> {
  const response = await apiFetch(`/api/share/${token}`);
  if (response.status === 404) return null;
  if (!response.ok) {
    throw new Error("Could not load shared meeting");
  }
  return (await response.json()) as PublicSharedSession;
}

export async function generateMetadata({
  params,
}: SharePageProps): Promise<Metadata> {
  const { token } = await params;
  const shared = await loadShared(token).catch(() => null);
  if (!shared) {
    return { title: "Mila — Shared meeting" };
  }
  return {
    title: `${shared.title} — Mila`,
    description: shared.notes.summary?.slice(0, 160) || "Shared meeting notes",
  };
}

export default async function SharePage({ params }: SharePageProps) {
  const { token } = await params;
  const shared = await loadShared(token);
  if (!shared) notFound();

  const formattedDate = new Date(shared.createdAt).toLocaleDateString(
    undefined,
    { year: "numeric", month: "long", day: "numeric" },
  );

  return (
    <div className="mila-app-bg min-h-screen">
      <header className="border-b border-[var(--border)] px-6 py-4">
        <div className="mx-auto flex max-w-3xl items-center justify-between">
          <BrandLogo />
          <Link
            href="/"
            className="mila-secondary rounded-lg border px-4 py-2 text-xs font-semibold transition"
          >
            Get Mila
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-12">
        <p className="mila-eyebrow text-[var(--accent)]">
          Shared meeting · {formattedDate}
        </p>
        <h1 className="mt-3 text-3xl font-semibold text-[var(--foreground)] sm:text-4xl">
          {shared.title}
        </h1>
        <p className="mila-muted mt-2 text-sm">
          Read-only summary generated by Mila. Anyone with this link can view.
        </p>

        <div className="mt-10 space-y-8">
          <Block title="Summary">
            {shared.notes.summary ? (
              <p className="text-base leading-7 text-slate-200">
                {shared.notes.summary}
              </p>
            ) : (
              <Empty text="No summary was produced for this meeting yet." />
            )}
          </Block>

          <Block title="Key points">
            {shared.notes.keyPoints.length ? (
              <ul className="space-y-2">
                {shared.notes.keyPoints.map((point) => (
                  <li
                    key={point}
                    className="flex gap-3 text-sm leading-6 text-[var(--foreground)]"
                  >
                    <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--accent)]" />
                    {point}
                  </li>
                ))}
              </ul>
            ) : (
              <Empty text="No key points captured." />
            )}
          </Block>

          <Block title="Action items">
            {shared.notes.actionItems.length ? (
              <ul className="space-y-2">
                {shared.notes.actionItems.map((item) => (
                  <li
                    key={item.id}
                    className="flex gap-3 text-sm leading-6 text-[var(--foreground)]"
                  >
                    <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-amber-300" />
                    <span>
                      {item.owner ? <strong>{item.owner}: </strong> : null}
                      {item.text}
                    </span>
                  </li>
                ))}
              </ul>
            ) : (
              <Empty text="No action items captured." />
            )}
          </Block>

          <Block title="Decisions">
            {shared.notes.decisions.length ? (
              <ul className="space-y-2">
                {shared.notes.decisions.map((decision) => (
                  <li
                    key={decision}
                    className="flex gap-3 text-sm leading-6 text-slate-200"
                  >
                    <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-sky-300" />
                    {decision}
                  </li>
                ))}
              </ul>
            ) : (
              <Empty text="No decisions captured." />
            )}
          </Block>
        </div>

        <footer className="mila-surface-raised mt-16 rounded-2xl border p-6 text-center">
          <p className="mila-muted text-sm">
            Want your meetings summarised like this?
          </p>
          <Link
            href="/"
            className="mila-primary mt-3 inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition"
          >
            Try Mila free
          </Link>
        </footer>
      </main>
    </div>
  );
}

function Block({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h2 className="mila-eyebrow">
        {title}
      </h2>
      <div className="mila-surface-raised mt-3 rounded-2xl border p-5">
        {children}
      </div>
    </section>
  );
}

function Empty({ text }: { text: string }) {
  return <p className="mila-muted text-sm">{text}</p>;
}
